/**
 * P6.3 HR→XML offline gate — the TS HR→XML converter must be byte-identical to
 * the C++ reference converter (`POST /api/hr-to-xml`) over the 216-step corpus.
 *
 * Fixtures in test/fixtures/hr-to-xml.json are generated by looping each corpus
 * HR line (the `hr` values from xml-to-hr.json) through the reference endpoint
 * with `emptyContext:true` + a non-existent `fileName`, so field/script/layout/
 * table object references resolve to the same context-free `id="0"` this offline
 * TS engine (no FMContext) produces. The `<Step id>` step-type id is real (a
 * catalog constant), so it byte-matches. Python has no HR→XML direction (the
 * agent writes fmxmlsnippet directly), so the C++ reference is the oracle here.
 *
 * Excluded: the 3 FM26-AI grammar-gap steps (Fine-Tune Model, Generate Response
 * from Model, Install Menu Set) that are out of scope for the whole program.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { hrToXml, loadCatalog } from '@/converter/hr-to-xml';
import type { StepCatalogEntry } from '@/converter/catalog-types';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const CATALOG_PATH = path.join(REPO_ROOT, 'agent', 'catalogs', 'step-catalog-en.json');
const FIXTURES_PATH = path.join(__dirname, 'fixtures', 'hr-to-xml.json');

/** FM26-AI grammar-gap steps excluded from every converter gate (plan §gaps). */
const EXCLUDED = new Set([
  'Fine-Tune Model',
  'Generate Response from Model',
  'Install Menu Set',
]);

interface Fixture {
  hr: string;
  xml: string;
}

const rawCatalog = JSON.parse(readFileSync(CATALOG_PATH, 'utf-8'));
const entries: StepCatalogEntry[] = rawCatalog.steps ?? rawCatalog;
loadCatalog(entries);

const fixtures: Record<string, Fixture> = JSON.parse(readFileSync(FIXTURES_PATH, 'utf-8'));

/** Step name = fixture-key basename without the `.xml` suffix. */
function stepNameOf(rel: string): string {
  return path.basename(rel).replace(/\.xml$/, '');
}

describe('HR→XML byte-identity vs C++ reference /api/hr-to-xml (216 corpus)', () => {
  const entriesArr = Object.entries(fixtures);

  it('covers all 216 corpus steps', () => {
    expect(entriesArr.length).toBe(216);
  });

  for (const [rel, fx] of entriesArr) {
    if (EXCLUDED.has(stepNameOf(rel))) {
      it.skip(`${rel} (FM26-AI grammar gap — excluded)`, () => {});
      continue;
    }
    it(rel, () => {
      expect(hrToXml(fx.hr).xml).toBe(fx.xml);
    });
  }
});
