/**
 * P6.3 primary offline gate — the TS XML→HR converter must be byte-identical to
 * the Python reference (agent/scripts/snippet_to_hr.py) over the whole 216-step
 * corpus. Fixtures in test/fixtures/xml-to-hr.json are generated by running the
 * Python pipeline over agent/snippet_examples/steps/**\/*.xml (see the P6.3 notes);
 * this test feeds each fixture's XML through the real browser-path xmlToHr and
 * asserts the output equals the recorded HR line exactly.
 *
 * The Python side was itself verified 215/216 byte-identical to the C++ reference
 * converter in P6.2, so matching Python inherits that validation. Both ports read
 * the SAME catalog (agent/catalogs/step-catalog-en.json), so this also proves the
 * two engines apply the catalog grammar identically.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { xmlToHr } from '@/converter/xml-to-hr';
import { initGrammar } from '@/converter/catalog-grammar';
import type { StepCatalogEntry } from '@/converter/catalog-types';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const CATALOG_PATH = path.join(REPO_ROOT, 'agent', 'catalogs', 'step-catalog-en.json');
const FIXTURES_PATH = path.join(__dirname, 'fixtures', 'xml-to-hr.json');

interface Fixture {
  xml: string;
  hr: string;
}

const rawCatalog = JSON.parse(readFileSync(CATALOG_PATH, 'utf-8'));
const entries: StepCatalogEntry[] = rawCatalog.steps ?? rawCatalog;
initGrammar(entries);

const fixtures: Record<string, Fixture> = JSON.parse(readFileSync(FIXTURES_PATH, 'utf-8'));

describe('XML→HR byte-identity vs Python snippet_to_hr (216 corpus)', () => {
  const entriesArr = Object.entries(fixtures);

  it('covers all 216 corpus steps', () => {
    expect(entriesArr.length).toBe(216);
  });

  for (const [rel, fx] of entriesArr) {
    it(rel, () => {
      expect(xmlToHr(fx.xml)).toBe(fx.hr);
    });
  }
});
